baseURL = "https://mlblogg.com/"
languageCode = "en-us"
title = "mlblogg"
theme = "ezhil"
paginate = 5

copyright = "© Copyright notice"

pygmentsstyle = "solarized-light"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ezhil-demo"

summaryLength = 20

[params]
	subtitle = "Hi, I'm Jon sharing my journey of learning ML/AI."
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "light" #"auto" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/mlblogg"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/mlblogg"



# [[params.social]]
# name = "RSS"
# icon = "rss"
# url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'pygments'
    tabWidth = 4